version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "CivicPulse_Dev123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P CivicPulse_Dev123! -Q 'SELECT 1' -C"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: src/CivicPulse.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      USE_INMEMORY: "0"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=CivicPulse;User Id=sa;Password=CivicPulse_Dev123!;TrustServerCertificate=True"
    depends_on:
      db:
        condition: service_healthy

volumes:
  sqldata:
